//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchases
    {
        public long PurchaseID { get; set; }
        public long CheckID { get; set; }
        public int ProductID { get; set; }
        public int ProductCount { get; set; }
    
        public virtual Checks Checks { get; set; }
        public virtual Products Products { get; set; }
    }
}
